### ISSUE TITLE
App

### ISSUE THREAD

**Issue by ghost** [apostrophecms/apostrophe-review-and-deploy#16]
Hello, can not create app. How and with what works? with me always shows 15 errors. Or can send me please apk file or manual for Termux installation.
My problem:
someone controll my phone and all others. Viewport / View Server ??? Writing software / code / uniform / Blink always finds my person. Can not use in Third Parties, Monitoring or Useful. I use gpu in first party and have no useful paths and can not see / look or feel. My GPU corrupt / ordinary and can not change. In groups or others my person displayed illegally privately. Have problem long and my person / psyche not good. Please help me to end problem and that I can use useful, thanks.

**Comment by boutell** [comment]
This module is unrelated to android or Termux and is intended for large deployments of ApostropheCMS.
